android:
  build:
    tools: 3.1.3
  fabric:
    tools: 1.25.4
    version: 2.9.4
  firebase:
    version: 16.0.1
    ads: 15.0.1
    analytics: 16.0.1 # part of core ??
    auth: 16.0.3
    config: 16.0.0
    core: 16.0.1
    crash: 16.0.1
    crashlytics: 2.9.4
    database: 16.0.2
    firestore: 17.1.0
    functions: 16.1.0
    invites: 16.0.3
    messaging: 17.3.3
    perf: 16.1.0
    storage: 16.0.2
    plugins: 1.1.1
  gms:
    google-services: 4.0.1
    play-services-base: 15.0.1
ios:
  fabric:
    tools: 1.7.11
    version: 3.10.4
  firebase:
    ads: 5.8.1
    auth: 5.8.1
    config: 5.8.1
    core: 5.8.1
    crash: 5.8.1
    crashlytics: 3.10.7
    database: 5.8.1
    firestore: 5.8.1
    functions: 5.8.1
    invites: 5.8.1
    links: 5.8.1
    messaging: 5.8.1
    perf: 5.8.1
    storage: 5.8.1
