android:
  build:
    tools: 3.3.2
  fabric:
    tools: 1.25.4
    version: 2.9.5
  firebase:
    version: 16.0.8
    ads: 15.0.1
    analytics: 16.4.0
    auth: 16.2.1
    config: 16.5.0
    core: 16.0.8
    crashlytics: 2.9.5
    database: 16.1.0
    firestore: 18.2.0
    functions: 16.3.0
    invites: 16.1.1
    messaging: 17.5.0
    perf: 16.2.5
    storage: 16.1.0
    plugins: 1.1.5
  gms:
    google-services: 4.2.0
    play-services-base: 16.1.0
ios:
  fabric:
    tools: 1.7.13
    version: 3.10.9
  firebase:
    ads: 5.15.0
    auth: 5.15.0
    config: 5.15.0
    core: 5.15.0
    crash: 5.15.0
    crashlytics: 3.10.7
    database: 5.15.0
    firestore: 5.15.0
    functions: 5.15.0
    invites: 5.15.0
    links: 5.15.0
    messaging: 5.15.0
    perf: 5.15.0
    storage: 5.15.0
