android:
  build:
    tools: 3.4.1
  fabric:
    tools: 1.28.1
  firebase:
    version: 16.0.9
    ads: 17.2.1
    analytics: 16.5.0
    auth: 17.0.0
    config: 17.0.0
    core: 16.0.9
    crashlytics: 2.9.9
    database: 17.0.0
    firestore: 19.0.0
    functions: 17.0.0
    links: 19.0.0
    in-app-messaging: 17.2.0
    invites: 17.0.0
    messaging: 18.0.0
    perf: 17.0.2
    storage: 17.0.0
    plugins: 1.2.1
  gms:
    google-services: 4.2.0
    play-services-base: 16.1.0
ios:
  fabric:
    tools: 1.10.2
  firebase:
    ads: 6.3.0
    auth: 6.3.0
    config: 6.3.0
    core: 6.3.0
    crash: 6.3.0
    crashlytics: 3.13.2
    database: 6.3.0
    firestore: 6.3.0
    functions: 6.3.0
    invites: 6.3.0
    links: 6.3.0
    messaging: 6.3.0
    perf: 6.3.0
    storage: 6.3.0
